name: first-action

on: 
   push:
    branches:
        - main

jobs:
    Create_file:
        runs-on: ubuntu-latest

        steps:
        - name: Check out Repo
          uses: actions/checkout@v6


        - name: Create file
          run: echo "This is my github actions training file" >> actions.txt

        - name: Git Push
          run: |
            git add .
            git commit -m "adding text file"
            git push origin main

    Test_file:
        needs: Create_file
        runs-on: ubuntu-latest

        steps:
        - name: Check out Repo
          uses: actions/checkout@v6

        - name: display content
          run: cat actions.txt

    Deploy_file: 
        needs: Test_file
        runs-on: ubuntu-latest

        steps:
        - name: Check out Repo
          uses: actions/checkout@v6

        - name: Deploy
          run: echo Deploying...

        - name: Check file
          run: grep -i actions.txt

