name: first-action

on: 
   push:
    branches:
        - main

jobs:
    Create_file:
        runs-on: ubuntu-latest

        steps:
        - name: Check out Repo
          uses: actions/checkout@v6


        - name: Create file
          run: echo "This is my github actions training file" >> actions.txt

        - name: upload-artifact  
          uses: actions/upload-artifact@v7
          with:
            name: actions-textfile
            path: actions.txt

    Test_file:
        needs: Create_file
        runs-on: ubuntu-latest

        steps:
        - name: Download artifact
          uses: actions/download-artifact@v8          
          with:
            name: actions-textfile

        - name: display content
          run: cat actions.txt

    Deploy_file: 
        needs: Test_file
        runs-on: ubuntu-latest

        steps:
        - name: Download artifact
          uses: actions/download-artifact@v8          
          with:
            name: actions-textfile

        - name: Deploy
          run: echo Deploying...

        - name: Check file
          run: grep -i actions.txt

